name: Generate Heatmap
on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 时间 00:00 运行
  workflow_dispatch:  # 允许手动触发
jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 添加此权限以允许提交和推送
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests svgwrite
      - name: Generate heatmap
        env:
          WEREAD_COOKIE: ${{ secrets.WEREAD_COOKIE }}
          START_YEAR: ${{ secrets.START_YEAR }}
          END_YEAR: ${{ secrets.END_YEAR }}
        run: python heatmap.py
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "action@github.com"
          git add heatmap.svg
          git commit -m "Update heatmap [skip ci]"
          git push
